version: "3.8"

services:
  backend:
    build:
      context: ./film-reel-backend
    ports:
      - "8000:8000"
    volumes:
      - ./film-reel-backend:/app
    environment:
      - PORT=8000
    depends_on:
      - redis

  frontend:
    build:
      context: ./film-reel-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
